build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
labels:
  org.opencontainers.image.title: "VereinsKnete"
  org.opencontainers.image.description: "Freelance time tracking and invoicing application"
  org.opencontainers.image.source: "https://github.com/jodli/vereinsknete-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  RUST_VERSION: "1.70"
  NODE_VERSION: "18"