name: "VereinsKnete"
version: "1.0.0"
slug: "vereinsknete"
description: "Freelance time tracking and invoicing application"
url: "https://github.com/jodli/vereinsknete-addon"
arch:
  - aarch64
  - amd64
startup: application
boot: manual
ingress: true
ingress_port: 8080
ingress_entry: "/"
panel_icon: "mdi:clock-time-four"
panel_title: "VereinsKnete"
webui: "http://[HOST]:[PORT:8080]"
options:
  database_path: "/data/vereinsknete.db"
  log_level: "info"
  port: 8080
  invoice_storage_path: "/data/invoices"
schema:
  database_path: "str"
  log_level: "list(debug|info|warn|error)"
  port: "port"
  invoice_storage_path: "str"
image: "ghcr.io/jodli/vereinsknete-addon-{arch}"