name: CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.github/**'
      - '.kiro/**'
  workflow_dispatch:
    inputs:
      version_name:
        description: "Version name for the release"
        required: false
        default: "manual-build"

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Extract version and determine deployment
        id: version
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          VERSION_NAME_INPUT: ${{ github.event.inputs.version_name }}
        run: |
          if [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            VERSION_NAME="$GITHUB_REF_NAME"
            VERSION_NAME="${VERSION_NAME#v}"  # Remove 'v' prefix
            DEPLOY_TARGET="production"
            IS_TAG_BUILD="true"
            echo "Tag build detected: $VERSION_NAME -> production release"
          elif [[ "$GITHUB_REF" == refs/heads/main ]]; then
            VERSION_NAME="main-$GITHUB_RUN_NUMBER"
            DEPLOY_TARGET="beta"
            IS_TAG_BUILD="false"
            echo "Main branch build: $VERSION_NAME -> open testing"
          else
            if [[ -z "$VERSION_NAME_INPUT" ]]; then
              VERSION_NAME="manual-build"
            else
              VERSION_NAME="$VERSION_NAME_INPUT"
            fi
            DEPLOY_TARGET="internal"
            IS_TAG_BUILD="false"
            echo "Manual build: $VERSION_NAME -> internal testing"
          fi

          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
          echo "deploy_target=$DEPLOY_TARGET" >> $GITHUB_OUTPUT
          echo "is_tag_build=$IS_TAG_BUILD" >> $GITHUB_OUTPUT

      - name: Set Version
        uses: chkfung/android-version-actions@b855905d688035ed881512403487c699f7d4986b
        with:
          gradlePath: android/app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          versionName: ${{ steps.version.outputs.version_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/*.gradle*', 'android/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          save: false
          lookup-only: true

      - name: Grant execute permission for gradlew
        working-directory: android
        run: chmod +x gradlew

      - name: Build release APK and AAB
        working-directory: android
        run: |
          ./gradlew assembleRelease bundleRelease
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Prepare release artifacts
        id: artifacts
        working-directory: android
        run: |
          # Find the generated files (Gradle handles the naming)
          APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -1)
          AAB_PATH=$(find app/build/outputs/bundle/release -name "*.aab" | head -1)

          # Extract the actual filenames generated by Gradle
          APK_NAME=$(basename "$APK_PATH")
          AAB_NAME=$(basename "$AAB_PATH")

          echo "apk_path=android/$APK_PATH" >> $GITHUB_OUTPUT
          echo "aab_path=android/$AAB_PATH" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yogaknete-${{ steps.version.outputs.version_name }}
          path: |
            ${{ steps.artifacts.outputs.apk_path }}
            ${{ steps.artifacts.outputs.aab_path }}

      - name: Generate GitHub release notes
        id: gen_release_notes
        env:
          VERSION_NAME_OUTPUT: ${{ steps.version.outputs.version_name }}
          IS_TAG_BUILD_OUTPUT: ${{ steps.version.outputs.is_tag_build }}
        run: |
          set -euo pipefail
          VERSION_NAME="$VERSION_NAME_OUTPUT"
          IS_TAG_BUILD="$IS_TAG_BUILD_OUTPUT"
          NOTES_FILE="RELEASE_NOTES.md"

          # Generate simple release notes
          if [[ "$IS_TAG_BUILD" == "true" ]]; then
            echo "# YogaKnete v${VERSION_NAME}" > "$NOTES_FILE"
            echo "" >> "$NOTES_FILE"
            echo "Release build of YogaKnete - Simple Yoga Class Tracker & Invoice Generator" >> "$NOTES_FILE"
            echo "" >> "$NOTES_FILE"
            echo "## What's New" >> "$NOTES_FILE"
            echo "- Built from tag v${VERSION_NAME}" >> "$NOTES_FILE"
          else
            echo "# YogaKnete (Latest Main)" > "$NOTES_FILE"
            echo "" >> "$NOTES_FILE"
            echo "Development build of YogaKnete from the main branch" >> "$NOTES_FILE"
            echo "" >> "$NOTES_FILE"
            echo "## Build Info" >> "$NOTES_FILE"
            echo "- Version: ${VERSION_NAME}" >> "$NOTES_FILE"
            echo "- Built from: main branch" >> "$NOTES_FILE"
            echo "- Commit: ${GITHUB_SHA:0:7}" >> "$NOTES_FILE"
          fi

          echo "notes_file=$NOTES_FILE" >> $GITHUB_OUTPUT

      - name: Print extracted release notes
        env:
          NOTES_FILE_OUTPUT: ${{ steps.gen_release_notes.outputs.notes_file }}
        run: |
          echo "=== Extracted release notes ($NOTES_FILE_OUTPUT) ==="
          cat "$NOTES_FILE_OUTPUT"
          echo "=== End of release notes ==="

      - name: Create or update GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NAME_OUTPUT: ${{ steps.version.outputs.version_name }}
          IS_TAG_BUILD_OUTPUT: ${{ steps.version.outputs.is_tag_build }}
          APK_PATH_OUTPUT: ${{ steps.artifacts.outputs.apk_path }}
          AAB_PATH_OUTPUT: ${{ steps.artifacts.outputs.aab_path }}
          NOTES_FILE_OUTPUT: ${{ steps.gen_release_notes.outputs.notes_file }}
        run: |
          VERSION_NAME="$VERSION_NAME_OUTPUT"
          IS_TAG_BUILD="$IS_TAG_BUILD_OUTPUT"
          APK_PATH="$APK_PATH_OUTPUT"
          AAB_PATH="$AAB_PATH_OUTPUT"
          NOTES_FILE="$NOTES_FILE_OUTPUT"

          if [[ "$IS_TAG_BUILD" == "true" ]]; then
            # Tag build - create new release
            TAG_NAME="v${VERSION_NAME}"
            RELEASE_TITLE="YogaKnete v${VERSION_NAME}"
            
            echo "Creating tag release: $TAG_NAME"
            
            gh release create "$TAG_NAME" \
              --title "$RELEASE_TITLE" \
              --notes-file "$NOTES_FILE" \
              "$APK_PATH" \
              "$AAB_PATH"
              
            echo "Created release: $RELEASE_TITLE"
          else
            # Main branch build - replace existing main release
            RELEASE_TAG="main-latest"
            RELEASE_TITLE="YogaKnete (Latest Main)"
            
            echo "Creating/updating main release: $RELEASE_TAG"
            
            # Delete existing release if it exists
            if gh release view "$RELEASE_TAG" > /dev/null 2>&1; then
              echo "Deleting existing main release..."
              gh release delete "$RELEASE_TAG" --yes
            fi
            
            # Create new release
            gh release create "$RELEASE_TAG" \
              --title "$RELEASE_TITLE" \
              --notes-file "$NOTES_FILE" \
              --prerelease \
              "$APK_PATH" \
              "$AAB_PATH"
              
            echo "Created/updated main release: $RELEASE_TITLE"
          fi

