name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: backend

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev pkg-config

    - name: Install Diesel CLI
      run: cargo install diesel_cli --no-default-features --features sqlite

    - name: Check formatting
      working-directory: ./backend
      run: cargo fmt --all -- --check

    - name: Run clippy
      working-directory: ./backend
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run backend tests
      working-directory: ./backend
      run: cargo test

    - name: Build backend
      working-directory: ./backend
      run: cargo build --release

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Run ESLint (if available)
      working-directory: ./frontend
      run: npm run lint --if-present || echo "No lint script found, skipping..."

    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --coverage --watchAll=false --passWithNoTests

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

  docker-build-test:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (test)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: vereinsknete:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
